import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://rds.onl'
  const routes = [
    '',
    '/introduction',
    '/getting-started',
    '/principles',
    '/guidelines',
    '/changelog',
    '/contributing',
    '/templates',
    '/patterns',
    '/tokens/colors',
    '/tokens/typography',
    '/tokens/spacing',
    '/tokens/shadows',
    '/tokens/motion',
    '/elements/ui/accordion',
    '/elements/ui/alert',
    '/elements/ui/alert-dialog',
    '/elements/ui/aspect-ratio',
    '/elements/ui/avatar',
    '/elements/ui/badge',
    '/elements/ui/breadcrumb',
    '/elements/ui/button',
    '/elements/ui/calendar',
    '/elements/ui/card',
    '/elements/ui/carousel',
    '/elements/ui/checkbox',
    '/elements/ui/collapsible',
    '/elements/ui/command',
    '/elements/ui/context-menu',
    '/elements/ui/dialog',
    '/elements/ui/drawer',
    '/elements/ui/dropdown-menu',
    '/elements/ui/form',
    '/elements/ui/hover-card',
    '/elements/ui/input',
    '/elements/ui/input-otp',
    '/elements/ui/label',
    '/elements/ui/menubar',
    '/elements/ui/navigation-menu',
    '/elements/ui/pagination',
    '/elements/ui/popover',
    '/elements/ui/progress',
    '/elements/ui/radio-group',
    '/elements/ui/resizable',
    '/elements/ui/scroll-area',
    '/elements/ui/select',
    '/elements/ui/separator',
    '/elements/ui/sheet',
    '/elements/ui/skeleton',
    '/elements/ui/slider',
    '/elements/ui/sonner',
    '/elements/ui/switch',
    '/elements/ui/table',
    '/elements/ui/tabs',
    '/elements/ui/textarea',
    '/elements/ui/toggle',
    '/elements/ui/toggle-group',
    '/elements/ui/tooltip',
    '/elements/media',
    '/elements/ai',
    '/elements/charts',
  ]
  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : 0.8,
  }))
}
